-- Historical reporting and operational audit foundations for the web admin.

create table if not exists public.job_status_history (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.jobs(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists job_status_history_job_time_idx
  on public.job_status_history (job_id, changed_at);

create table if not exists public.booking_status_history (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists booking_status_history_booking_time_idx
  on public.booking_status_history (booking_id, changed_at);

create table if not exists public.marketplace_daily_snapshots (
  snapshot_date date primary key,
  total_users integer not null,
  total_jobs integer not null,
  open_jobs integer not null,
  completed_jobs integer not null,
  cancelled_jobs integer not null,
  active_services integer not null,
  active_bookings integer not null,
  captured_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log (created_at desc);

alter table public.job_status_history enable row level security;
alter table public.booking_status_history enable row level security;
alter table public.marketplace_daily_snapshots enable row level security;
alter table public.admin_audit_log enable row level security;

create policy "Admins read job status history"
  on public.job_status_history for select to authenticated
  using (public.current_user_is_admin());
create policy "Admins read booking status history"
  on public.booking_status_history for select to authenticated
  using (public.current_user_is_admin());
create policy "Admins read marketplace snapshots"
  on public.marketplace_daily_snapshots for select to authenticated
  using (public.current_user_is_admin());
create policy "Admins read admin audit log"
  on public.admin_audit_log for select to authenticated
  using (public.current_user_is_admin());
create policy "Admins write admin audit log"
  on public.admin_audit_log for insert to authenticated
  with check (public.current_user_is_admin() and admin_id = auth.uid());

grant select on public.job_status_history, public.booking_status_history,
  public.marketplace_daily_snapshots, public.admin_audit_log to authenticated;
grant insert on public.admin_audit_log to authenticated;
grant all on public.job_status_history, public.booking_status_history,
  public.marketplace_daily_snapshots, public.admin_audit_log to service_role;

create or replace function public.capture_job_status_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.job_status_history (job_id, from_status, to_status, changed_by, changed_at)
    values (
      new.id,
      case when tg_op = 'INSERT' then null else old.status end,
      new.status,
      auth.uid(),
      case when tg_op = 'INSERT' then new.created_at else now() end
    );
  end if;
  return new;
end;
$$;

drop trigger if exists jobs_capture_status_history on public.jobs;
create trigger jobs_capture_status_history
  after insert or update of status on public.jobs
  for each row execute function public.capture_job_status_history();

create or replace function public.capture_booking_status_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.booking_status_history (booking_id, from_status, to_status, changed_by, changed_at)
    values (
      new.id,
      case when tg_op = 'INSERT' then null else old.status end,
      new.status,
      auth.uid(),
      case when tg_op = 'INSERT' then new.created_at else now() end
    );
  end if;
  return new;
end;
$$;

drop trigger if exists bookings_capture_status_history on public.bookings;
create trigger bookings_capture_status_history
  after insert or update of status on public.bookings
  for each row execute function public.capture_booking_status_history();

-- Existing rows establish a baseline without inventing historical transition
-- dates. Accurate lifecycle durations therefore begin with this migration.
insert into public.job_status_history (job_id, from_status, to_status, changed_at)
select j.id, null, j.status, now()
  from public.jobs j
 where not exists (select 1 from public.job_status_history h where h.job_id = j.id);

insert into public.booking_status_history (booking_id, from_status, to_status, changed_at)
select b.id, null, b.status, now()
  from public.bookings b
 where not exists (select 1 from public.booking_status_history h where h.booking_id = b.id);

create or replace function public.capture_marketplace_daily_snapshot()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.marketplace_daily_snapshots (
    snapshot_date, total_users, total_jobs, open_jobs, completed_jobs,
    cancelled_jobs, active_services, active_bookings, captured_at
  ) values (
    (now() at time zone 'Pacific/Auckland')::date,
    (select count(*)::integer from public.profiles),
    (select count(*)::integer from public.jobs),
    (select count(*)::integer from public.jobs where status = 'open'),
    (select count(*)::integer from public.jobs where status = 'completed'),
    (select count(*)::integer from public.jobs where status = 'cancelled'),
    (select count(*)::integer from public.services where is_active),
    (select count(*)::integer from public.bookings where status in (
      'pending', 'quote_sent', 'confirmed', 'in_progress',
      'awaiting_completion', 'cancellation_requested'
    )),
    now()
  )
  on conflict (snapshot_date) do update set
    total_users = excluded.total_users,
    total_jobs = excluded.total_jobs,
    open_jobs = excluded.open_jobs,
    completed_jobs = excluded.completed_jobs,
    cancelled_jobs = excluded.cancelled_jobs,
    active_services = excluded.active_services,
    active_bookings = excluded.active_bookings,
    captured_at = excluded.captured_at;
end;
$$;

revoke all on function public.capture_marketplace_daily_snapshot() from public;
grant execute on function public.capture_marketplace_daily_snapshot() to service_role;

select public.capture_marketplace_daily_snapshot();

select cron.unschedule(jobid)
  from cron.job
 where jobname = 'capture-marketplace-daily-snapshot';

select cron.schedule(
  'capture-marketplace-daily-snapshot',
  '5 12 * * *',
  $$select public.capture_marketplace_daily_snapshot();$$
);
